class MainController < ApplicationController

  def home
    @programs = Program.all
    @modules = Course.all
    @students = Student.all
    # will eventually only hold the data for the given search/filter options
    # but that's a future problem :)
    @filtered_data = {
        data: [
          {
            Surname: "Aqua",
            Forename: "Ruth",
            "Reg No.": "000000000",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "82",
            "2nd Grade": "-",
          },
          {
            Surname: "Blue",
            Forename: "Kathy",
            "Reg No.": "000000001",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "50",
            "2nd Grade": "-",
          },
          {
            Surname: "Clementine",
            Forename: "Ruth",
            "Reg No.": "000000002",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "51",
            "2nd Grade": "-",
          },
          {
            Surname: "Denim",
            Forename: "Rebecca",
            "Reg No.": "000000003",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "52",
            "2nd Grade": "-",
          },
          {
            Surname: "Ecru",
            Forename: "Emily",
            "Reg No.": "000000004",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "53",
            "2nd Grade": "-",
          },
          {
            Surname: "Forrest",
            Forename: "Gemma",
            "Reg No.": "000000005",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "54",
            "2nd Grade": "-",
          },
          {
            Surname: "Green",
            Forename: "Timothy",
            "Reg No.": "000000006",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "55",
            "2nd Grade": "-",
          },
          {
            Surname: "Harlequin",
            Forename: "Kyriaki",
            "Reg No.": "000000007",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "56",
            "2nd Grade": "-",
          },
          {
            Surname: "Indigo",
            Forename: "Alyssa",
            "Reg No.": "000000008",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "57",
            "2nd Grade": "-",
          },
          {
            Surname: "Jade",
            Forename: "Andrea",
            "Reg No.": "000000009",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "5",
            "2nd Grade": "-",
          },
          {
            Surname: "KeyLime",
            Forename: "Diana",
            "Reg No.": "000000010",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "56",
            "2nd Grade": "-",
          },
          {
            Surname: "Lemon",
            Forename: "Pim",
            "Reg No.": "000000011",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "DE",
            "2nd Grade": "-",
          },
          {
            Surname: "Magenta",
            Forename: "Lauren",
            "Reg No.": "000000012",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "70",
            "2nd Grade": "-",
          },
          {
            Surname: "Noir",
            Forename: "Hannah",
            "Reg No.": "000000013",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "67",
            "2nd Grade": "-",
          },
          {
            Surname: "Opal",
            Forename: "Miranda",
            "Reg No.": "000000014",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "52",
            "2nd Grade": "-",
          },
          {
            Surname: "Peach",
            Forename: "Nichola",
            "Reg No.": "000000015",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "68",
            "2nd Grade": "-",
          },
        ],
        errors: [],
        meta: {
          delimiter: ",",
          linebreak: "\r\n",
          aborted: false,
          truncated: false,
          cursor: 919,
          fields: [
            "Surname",
            "Forename",
            "Reg No.",
            "Reg. Status",
            "Module Code",
            "1st Grade",
            "2nd Grade",
          ],
        },
      }
    # holds all the data from the csv file
      @data = [
      {
        data: [
          {
            Surname: "Aqua",
            Forename: "Ruth",
            "Reg No.": "000000000",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "82",
            "2nd Grade": "-",
          },
          {
            Surname: "Blue",
            Forename: "Kathy",
            "Reg No.": "000000001",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "50",
            "2nd Grade": "-",
          },
          {
            Surname: "Clementine",
            Forename: "Ruth",
            "Reg No.": "000000002",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "51",
            "2nd Grade": "-",
          },
          {
            Surname: "Denim",
            Forename: "Rebecca",
            "Reg No.": "000000003",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "52",
            "2nd Grade": "-",
          },
          {
            Surname: "Ecru",
            Forename: "Emily",
            "Reg No.": "000000004",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "53",
            "2nd Grade": "-",
          },
          {
            Surname: "Forrest",
            Forename: "Gemma",
            "Reg No.": "000000005",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "54",
            "2nd Grade": "-",
          },
          {
            Surname: "Green",
            Forename: "Timothy",
            "Reg No.": "000000006",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "55",
            "2nd Grade": "-",
          },
          {
            Surname: "Harlequin",
            Forename: "Kyriaki",
            "Reg No.": "000000007",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "56",
            "2nd Grade": "-",
          },
          {
            Surname: "Indigo",
            Forename: "Alyssa",
            "Reg No.": "000000008",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "57",
            "2nd Grade": "-",
          },
          {
            Surname: "Jade",
            Forename: "Andrea",
            "Reg No.": "000000009",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "5",
            "2nd Grade": "-",
          },
          {
            Surname: "KeyLime",
            Forename: "Diana",
            "Reg No.": "000000010",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "56",
            "2nd Grade": "-",
          },
          {
            Surname: "Lemon",
            Forename: "Pim",
            "Reg No.": "000000011",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "DE",
            "2nd Grade": "-",
          },
          {
            Surname: "Magenta",
            Forename: "Lauren",
            "Reg No.": "000000012",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "70",
            "2nd Grade": "-",
          },
          {
            Surname: "Noir",
            Forename: "Hannah",
            "Reg No.": "000000013",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "67",
            "2nd Grade": "-",
          },
          {
            Surname: "Opal",
            Forename: "Miranda",
            "Reg No.": "000000014",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "52",
            "2nd Grade": "-",
          },
          {
            Surname: "Peach",
            Forename: "Nichola",
            "Reg No.": "000000015",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS642",
            "1st Grade": "68",
            "2nd Grade": "-",
          },
        ],
        errors: [],
        meta: {
          delimiter: ",",
          linebreak: "\r\n",
          aborted: false,
          truncated: false,
          cursor: 919,
          fields: [
            "Surname",
            "Forename",
            "Reg No.",
            "Reg. Status",
            "Module Code",
            "1st Grade",
            "2nd Grade",
          ],
        },
      },
      {
        data: [
          {
            Surname: "Aqua",
            Forename: "Ruth",
            "Reg No.": "000000000",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6025",
            "1st Grade": "57",
            "2nd Grade": "-",
          },
          {
            Surname: "Blue",
            Forename: "Kathy",
            "Reg No.": "000000001",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6025",
            "1st Grade": "56",
            "2nd Grade": "-",
          },
          {
            Surname: "Clementine",
            Forename: "Ruth",
            "Reg No.": "000000002",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6025",
            "1st Grade": "67",
            "2nd Grade": "-",
          },
          {
            Surname: "Denim",
            Forename: "Rebecca",
            "Reg No.": "000000003",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6025",
            "1st Grade": "45",
            "2nd Grade": "-",
          },
          {
            Surname: "Ecru",
            Forename: "Emily",
            "Reg No.": "000000004",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6025",
            "1st Grade": "34",
            "2nd Grade": "-",
          },
          {
            Surname: "Forrest",
            Forename: "Gemma",
            "Reg No.": "000000005",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6025",
            "1st Grade": "17",
            "2nd Grade": "-",
          },
          {
            Surname: "Green",
            Forename: "Timothy",
            "Reg No.": "000000006",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6025",
            "1st Grade": "52",
            "2nd Grade": "-",
          },
          {
            Surname: "Harlequin",
            Forename: "Kyriaki",
            "Reg No.": "000000007",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6025",
            "1st Grade": "53",
            "2nd Grade": "-",
          },
          {
            Surname: "Indigo",
            Forename: "Alyssa",
            "Reg No.": "000000008",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6025",
            "1st Grade": "54",
            "2nd Grade": "-",
          },
          {
            Surname: "Jade",
            Forename: "Andrea",
            "Reg No.": "000000009",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6025",
            "1st Grade": "NC",
            "2nd Grade": "-",
          },
          {
            Surname: "KeyLime",
            Forename: "Diana",
            "Reg No.": "000000010",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6025",
            "1st Grade": "67",
            "2nd Grade": "-",
          },
          {
            Surname: "Lemon",
            Forename: "Pim",
            "Reg No.": "000000011",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6025",
            "1st Grade": "65",
            "2nd Grade": "-",
          },
          {
            Surname: "Magenta",
            Forename: "Lauren",
            "Reg No.": "000000012",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6025",
            "1st Grade": "56",
            "2nd Grade": "-",
          },
          {
            Surname: "Noir",
            Forename: "Hannah",
            "Reg No.": "000000013",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6025",
            "1st Grade": "56",
            "2nd Grade": "-",
          },
          {
            Surname: "Opal",
            Forename: "Miranda",
            "Reg No.": "000000014",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6025",
            "1st Grade": "67",
            "2nd Grade": "-",
          },
          {
            Surname: "Peach",
            Forename: "Nichola",
            "Reg No.": "000000015",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6025",
            "1st Grade": "68",
            "2nd Grade": "-",
          },
        ],
        errors: [],
        meta: {
          delimiter: ",",
          linebreak: "\r\n",
          aborted: false,
          truncated: false,
          cursor: 936,
          fields: [
            "Surname",
            "Forename",
            "Reg No.",
            "Reg. Status",
            "Module Code",
            "1st Grade",
            "2nd Grade",
          ],
        },
      },
      {
        data: [
          {
            Surname: "Aqua",
            Forename: "Ruth",
            "Reg No.": "000000000",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6026",
            "1st Grade": "56",
            "2nd Grade": "-",
          },
          {
            Surname: "Blue",
            Forename: "Kathy",
            "Reg No.": "000000001",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6026",
            "1st Grade": "57",
            "2nd Grade": "-",
          },
          {
            Surname: "Clementine",
            Forename: "Ruth",
            "Reg No.": "000000002",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6026",
            "1st Grade": "58",
            "2nd Grade": "-",
          },
          {
            Surname: "Denim",
            Forename: "Rebecca",
            "Reg No.": "000000003",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6026",
            "1st Grade": "56",
            "2nd Grade": "-",
          },
          {
            Surname: "Ecru",
            Forename: "Emily",
            "Reg No.": "000000004",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6026",
            "1st Grade": "64",
            "2nd Grade": "-",
          },
          {
            Surname: "Forrest",
            Forename: "Gemma",
            "Reg No.": "000000005",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6026",
            "1st Grade": "35",
            "2nd Grade": "-",
          },
          {
            Surname: "Green",
            Forename: "Timothy",
            "Reg No.": "000000006",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6026",
            "1st Grade": "67",
            "2nd Grade": "-",
          },
          {
            Surname: "Harlequin",
            Forename: "Kyriaki",
            "Reg No.": "000000007",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6026",
            "1st Grade": "65",
            "2nd Grade": "-",
          },
          {
            Surname: "Indigo",
            Forename: "Alyssa",
            "Reg No.": "000000008",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6026",
            "1st Grade": "64",
            "2nd Grade": "-",
          },
          {
            Surname: "Jade",
            Forename: "Andrea",
            "Reg No.": "000000009",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6026",
            "1st Grade": "70",
            "2nd Grade": "-",
          },
          {
            Surname: "KeyLime",
            Forename: "Diana",
            "Reg No.": "000000010",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6026",
            "1st Grade": "53",
            "2nd Grade": "-",
          },
          {
            Surname: "Lemon",
            Forename: "Pim",
            "Reg No.": "000000011",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6026",
            "1st Grade": "69",
            "2nd Grade": "-",
          },
          {
            Surname: "Magenta",
            Forename: "Lauren",
            "Reg No.": "000000012",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6026",
            "1st Grade": "69",
            "2nd Grade": "-",
          },
          {
            Surname: "Noir",
            Forename: "Hannah",
            "Reg No.": "000000013",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6026",
            "1st Grade": "NA",
            "2nd Grade": "-",
          },
          {
            Surname: "Opal",
            Forename: "Miranda",
            "Reg No.": "000000014",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6026",
            "1st Grade": "57",
            "2nd Grade": "-",
          },
          {
            Surname: "Peach",
            Forename: "Nichola",
            "Reg No.": "000000015",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6026",
            "1st Grade": "65",
            "2nd Grade": "-",
          },
        ],
        errors: [],
        meta: {
          delimiter: ",",
          linebreak: "\r\n",
          aborted: false,
          truncated: false,
          cursor: 936,
          fields: [
            "Surname",
            "Forename",
            "Reg No.",
            "Reg. Status",
            "Module Code",
            "1st Grade",
            "2nd Grade",
          ],
        },
      },
      {
        data: [
          {
            Surname: "Aqua",
            Forename: "Ruth",
            "Reg No.": "000000000",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6080",
            "1st Grade": "65",
            "2nd Grade": "-",
          },
          {
            Surname: "Blue",
            Forename: "Kathy",
            "Reg No.": "000000001",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6080",
            "1st Grade": "75",
            "2nd Grade": "-",
          },
          {
            Surname: "Clementine",
            Forename: "Ruth",
            "Reg No.": "000000002",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6080",
            "1st Grade": "69",
            "2nd Grade": "-",
          },
          {
            Surname: "Denim",
            Forename: "Rebecca",
            "Reg No.": "000000003",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6080",
            "1st Grade": "60",
            "2nd Grade": "-",
          },
          {
            Surname: "Ecru",
            Forename: "Emily",
            "Reg No.": "000000004",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6080",
            "1st Grade": "66",
            "2nd Grade": "-",
          },
          {
            Surname: "Forrest",
            Forename: "Gemma",
            "Reg No.": "000000005",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6080",
            "1st Grade": "58",
            "2nd Grade": "-",
          },
          {
            Surname: "Green",
            Forename: "Timothy",
            "Reg No.": "000000006",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6080",
            "1st Grade": "51",
            "2nd Grade": "-",
          },
          {
            Surname: "Harlequin",
            Forename: "Kyriaki",
            "Reg No.": "000000007",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6080",
            "1st Grade": "65",
            "2nd Grade": "-",
          },
          {
            Surname: "Indigo",
            Forename: "Alyssa",
            "Reg No.": "000000008",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6080",
            "1st Grade": "64",
            "2nd Grade": "-",
          },
          {
            Surname: "Jade",
            Forename: "Andrea",
            "Reg No.": "000000009",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6080",
            "1st Grade": "71",
            "2nd Grade": "-",
          },
          {
            Surname: "KeyLime",
            Forename: "Diana",
            "Reg No.": "000000010",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6080",
            "1st Grade": "52",
            "2nd Grade": "-",
          },
          {
            Surname: "Lemon",
            Forename: "Pim",
            "Reg No.": "000000011",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6080",
            "1st Grade": "71",
            "2nd Grade": "-",
          },
          {
            Surname: "Magenta",
            Forename: "Lauren",
            "Reg No.": "000000012",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6080",
            "1st Grade": "70",
            "2nd Grade": "-",
          },
          {
            Surname: "Noir",
            Forename: "Hannah",
            "Reg No.": "000000013",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6080",
            "1st Grade": "68",
            "2nd Grade": "-",
          },
          {
            Surname: "Opal",
            Forename: "Miranda",
            "Reg No.": "000000014",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6080",
            "1st Grade": "51",
            "2nd Grade": "-",
          },
          {
            Surname: "Peach",
            Forename: "Nichola",
            "Reg No.": "000000015",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6080",
            "1st Grade": "68",
            "2nd Grade": "-",
          },
        ],
        errors: [],
        meta: {
          delimiter: ",",
          linebreak: "\r\n",
          aborted: false,
          truncated: false,
          cursor: 936,
          fields: [
            "Surname",
            "Forename",
            "Reg No.",
            "Reg. Status",
            "Module Code",
            "1st Grade",
            "2nd Grade",
          ],
        },
      },
      {
        data: [
          {
            Surname: "Aqua",
            Forename: "Ruth",
            "Reg No.": "000000000",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6090",
            "1st Grade": "59",
            "2nd Grade": "-",
          },
          {
            Surname: "Blue",
            Forename: "Kathy",
            "Reg No.": "000000001",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6090",
            "1st Grade": "21",
            "2nd Grade": "-",
          },
          {
            Surname: "Clementine",
            Forename: "Ruth",
            "Reg No.": "000000002",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6090",
            "1st Grade": "33",
            "2nd Grade": "-",
          },
          {
            Surname: "Denim",
            Forename: "Rebecca",
            "Reg No.": "000000003",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6090",
            "1st Grade": "60",
            "2nd Grade": "-",
          },
          {
            Surname: "Ecru",
            Forename: "Emily",
            "Reg No.": "000000004",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6090",
            "1st Grade": "67",
            "2nd Grade": "-",
          },
          {
            Surname: "Forrest",
            Forename: "Gemma",
            "Reg No.": "000000005",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6090",
            "1st Grade": "81",
            "2nd Grade": "-",
          },
          {
            Surname: "Green",
            Forename: "Timothy",
            "Reg No.": "000000006",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6090",
            "1st Grade": "DE",
            "2nd Grade": "-",
          },
          {
            Surname: "Harlequin",
            Forename: "Kyriaki",
            "Reg No.": "000000007",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6090",
            "1st Grade": "NA",
            "2nd Grade": "-",
          },
          {
            Surname: "Indigo",
            Forename: "Alyssa",
            "Reg No.": "000000008",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6090",
            "1st Grade": "64",
            "2nd Grade": "-",
          },
          {
            Surname: "Jade",
            Forename: "Andrea",
            "Reg No.": "000000009",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6090",
            "1st Grade": "71",
            "2nd Grade": "-",
          },
          {
            Surname: "KeyLime",
            Forename: "Diana",
            "Reg No.": "000000010",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6090",
            "1st Grade": "52",
            "2nd Grade": "-",
          },
          {
            Surname: "Lemon",
            Forename: "Pim",
            "Reg No.": "000000011",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6090",
            "1st Grade": "56",
            "2nd Grade": "-",
          },
          {
            Surname: "Magenta",
            Forename: "Lauren",
            "Reg No.": "000000012",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6090",
            "1st Grade": "57",
            "2nd Grade": "-",
          },
          {
            Surname: "Noir",
            Forename: "Hannah",
            "Reg No.": "000000013",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6090",
            "1st Grade": "58",
            "2nd Grade": "-",
          },
          {
            Surname: "Opal",
            Forename: "Miranda",
            "Reg No.": "000000014",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6090",
            "1st Grade": "57",
            "2nd Grade": "-",
          },
          {
            Surname: "Peach",
            Forename: "Nichola",
            "Reg No.": "000000015",
            "Reg. Status": "Fully registered",
            "Module Code": "MUS6090",
            "1st Grade": "54",
            "2nd Grade": "-",
          },
        ],
        errors: [],
        meta: {
          delimiter: ",",
          linebreak: "\r\n",
          aborted: false,
          truncated: false,
          cursor: 936,
          fields: [
            "Surname",
            "Forename",
            "Reg No.",
            "Reg. Status",
            "Module Code",
            "1st Grade",
            "2nd Grade",
          ],
        },
      },
    ]
    @search = ""
    @module_index = 0
  end

  # the rest of this shit doesn't work so feel free to get rid of it
  def set_filtered_data
    @filtered_data = @data[@module_index]
  end

  def set_module_index
    @module_index = params[:module_index].to_i
    respond_to do |format|
    format.js { render js: "console.log('Successfully updated module index');" }
    end
    set_filtered_data
  end

  def set_search(string)
    @search = string
  end

  def filter_data
    if @search == ""
      set_filtered_data
    else
      filtered_data = []

      @data[@module_index].each do |row|
        row.each do |key, value|
          if value.downcase.include? @search.downcase
            filtered_data << row
            break
          end
        end
      end

      @filtered_data = filtered_data
    end
  end
end